### ISSUE TITLE
Reoptimize artikel - Perbedaan saham dan obligasi

### ISSUE THREAD

**Issue by rifdarum** [davidgalak/InvestasiKu#23]

**Comment by davidgalak** [comment]
**Reoptimize Apa Perbedaan Saham dan Obligasi?**
URL: https://www.investasiku.id/eduvest/saham/perbedaan-saham-dan-obligasi
Judul

### List Update:
1. Update Judul Artikel
2. Update Meta Desc
3. Update Artikel & Fokus Keyword

H2: Apa itu Saham
H2: Apa itu Obligasi
H2: Perbedaan Saham dan Obligasi
  H3: 
  H3:
  H3:
  H3:
  H3:
H2: Mana yang Cocok untuk Investasi? Saham Atau Obligasi?

**Comment by rifdarum** [comment]
https://docs.google.com/document/d/1z3d6HlRFRzZcPpGbAuvcpT_ziql9Kon4i-heK0026EU/edit

**Comment by davidgalak** [comment]
Udah review move to draft
