### ISSUE TITLE
Reoptimize artikel - Stock Split Adalah

### ISSUE THREAD

**Issue by rifdarum** [davidgalak/InvestasiKu#42]

**Comment by davidgalak** [comment]
Reoptimize artikel dengan judul **[Stock Split Adalah: Apa Alasan Perusahaan Melakukan itu?](https://www.investasiku.id/eduvest/saham/stock-split-adalah)**

Artikel ini perlu di ubah:

1. Judul artikel dibuat lebih sesuai intens
2. Update meta desc
3. Tambahkan opening pada artikel
4. Tambahkan kesimpulan artikel dengan CTA 
5. Update Featured image
6. Update tanggal publish

**Comment by rifdarum** [comment]
https://docs.google.com/document/d/1gfQQutVZ3VNCVAkAo25DFOfvgOoiZA43UvD0cLUOelA/edit
