### ISSUE TITLE
Reoptimize artikel - Investasi saham untuk pemula

### ISSUE THREAD

**Issue by rifdarum** [davidgalak/InvestasiKu#43]

**Comment by davidgalak** [comment]
Update Artikel dengan judul **[Investasi Saham untuk Pemula Beserta 11 Tips Bermanfaat](https://www.investasiku.id/eduvest/saham/investasi-saham-untuk-pemula)**

Berikut yang perlu diupdate:

1. Judul Artikel
2. Meta desc
3. Featured image
4. Tanggal publish
5. Ubah bagian yang membahas tentang investasi pemula di taruh lebih awal
6. Tambahkan poin investasi untuk pemula jika ada dan bisa lebih dari 11
