### ISSUE TITLE
Reoptimize artikel - Averaging Down Saham

### ISSUE THREAD

**Issue by rifdarum** [davidgalak/InvestasiKu#44]

**Comment by davidgalak** [comment]
Artikel yang perlu di update berjudul [**Averaging Down Saham: Manfaat, Kekurangan, & Cara Menggunakan**](https://www.investasiku.id/eduvest/saham/avg-saham-adalah-pengertian-contoh)

Yang harus di update:

1. Meta Desc
2. Judul artikel (dengan keyword utama Averaging Down Saham)
3. Tambahkan opening yang lebih bagus
4. Tambahkan heading **Apa itu Averaging Down Sama**
5.  Tambahkan kesimpulan dengan CTA yang mengarahkan ke refferal SEO
6. Update banner
