### ISSUE TITLE
Reoptimize artikel - Sideways Pada Saham

### ISSUE THREAD

**Issue by rifdarum** [davidgalak/InvestasiKu#47]
Artikel dengan judul **[Sideways Pada Saham: Identifikasi Trend dan Strategi Trading](https://www.investasiku.id/eduvest/saham/sideways-pada-saham-identifikasi-trend-dan-strategi-trading)** harus di re-optimize, yang harus di optimasi:

1. Ubah Title sesuai dengan intents dan competitor
2. Update meta desc
3. Tambahkan H2 **Apa itu Sideways Saham**
4. Ubah banner + link refferal pada artikel
5. Tambahkan kesimpulan dan CTA yang mengarahkan ke product page

**Comment by davidgalak** [comment]
Artikel dengan judul **[Sideways Pada Saham: Identifikasi Trend dan Strategi Trading](https://www.investasiku.id/eduvest/saham/sideways-pada-saham-identifikasi-trend-dan-strategi-trading)** harus di re-optimize, yang harus di optimasi:

1. Ubah Title sesuai dengan intents dan competitor
2. Update meta desc
3. Tambahkan H2 **Apa itu Sideways Saham**
4. Ubah banner + link refferal pada artikel
5. Tambahkan kesimpulan dan CTA yang mengarahkan ke product page

**Comment by rifdarum** [comment]
https://docs.google.com/document/d/13fmqlIyNmqSPkVD9s_n9UCUl6LtKX3dl2IKMrKzyy8s/edit
